# Generated by Django 3.2.7 on 2021-12-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm',
            name='recepient',
        ),
        migrations.AddField(
            model_name='pm',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='recceiver',
        ),
    ]
