# Generated by Django 3.2.7 on 2021-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211222_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ManyToManyField(related_name='tags', to='application.Category'),
        ),
    ]
